<?php

namespace Drupal\geoff_module\Controller;

use Symfony\Component\HttpFoundation\Response;

class GeoffController
{

  public function geoff()
  {
return [
      '#markup' => '<h3>' . t('Welcome to my first themed Drupal 8 webpage generated by a custom module.') . '</h3><p>' . t('Skateboard for life!') . '</p>',
    ];
  }

}






